# Generated by Django 3.1.3 on 2020-12-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201206_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
