# Generated by Django 3.1.3 on 2020-12-07 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201207_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
