# Generated by Django 3.1.3 on 2020-12-08 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_report_time_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('total_ratings', models.IntegerField(default=0)),
                ('avg_ratings', models.FloatField(default=0.0)),
                ('tag', models.CharField(choices=[('A', 'Appetizers'), ('S', 'Salads'), ('C', 'Chicken'), ('B', 'Beef'), ('P', 'Pork'), ('D', 'Desserts')], max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('last_ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dish_chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.chef')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dining_option',
            field=models.CharField(choices=[('DI', 'Dine In'), ('D', 'Delivery'), ('P', 'Pickup')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=12500, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.MenuItems'),
        ),
    ]
