# Generated by Django 3.1.3 on 2020-12-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20201208_2020'),
        ('restaurant', '0008_auto_20201208_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
