# Generated by Django 3.1.3 on 2020-12-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_delete_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='type',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='type',
        ),
    ]
