# Generated by Django 3.1.3 on 2020-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20201209_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
