# Generated by Django 3.1.3 on 2020-12-09 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20201209_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
