# Generated by Django 3.1.3 on 2020-12-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dishes',
        ),
    ]
