# Generated by Django 3.1.2 on 2020-12-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_remove_orders_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.deliveryperson'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='chef_prepared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.chef'),
        ),
    ]
