# Generated by Django 3.1.3 on 2020-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20201210_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCompliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('C', 'Customer'), ('DP', 'Delivery Person')], max_length=2)),
                ('recipient', models.CharField(choices=[('C', 'Customer'), ('DP', 'Delivery Person'), ('CH', 'Chef')], max_length=2)),
                ('sender_pk', models.IntegerField(default=-1, null=True)),
                ('recipient_pk', models.IntegerField(default=-1, null=True)),
                ('type', models.CharField(choices=[('CA', 'Complaint'), ('CI', 'Compliment')], max_length=2)),
                ('body', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deliveryperson',
            options={'verbose_name': 'Delivery Person', 'verbose_name_plural': 'Delivery People'},
        ),
    ]
