# Generated by Django 3.1.3 on 2020-12-10 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0021_auto_20201210_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliments',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='compliments',
            name='recipient_type',
        ),
        migrations.RemoveField(
            model_name='compliments',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='compliments',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='compliments',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compliments_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliments',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compliments_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
