# Generated by Django 3.1.3 on 2020-12-11 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0024_auto_20201210_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='recipient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='sender',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliments',
            name='recipient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliments_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliments',
            name='sender',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliments_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
