# Generated by Django 3.1.2 on 2020-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_auto_20201210_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_VIP',
            field=models.BooleanField(default=False),
        ),
    ]
