# Generated by Django 3.1.2 on 2020-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20201210_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='dish',
            name='num_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
