# Generated by Django 3.1.2 on 2020-12-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_auto_20201210_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(choices=[('SP', 'Specials'), ('F', 'Featured'), ('A', 'Appetizers'), ('S', 'Salads'), ('C', 'Chicken'), ('B', 'Beef'), ('P', 'Pork'), ('D', 'Desserts')], max_length=2),
        ),
    ]
