# Generated by Django 3.1.2 on 2020-12-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_auto_20201210_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.Dish'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(choices=[('SP', 'Specials'), ('A', 'Appetizers'), ('S', 'Salads'), ('C', 'Chicken'), ('B', 'Beef'), ('P', 'Pork'), ('D', 'Desserts')], max_length=2),
        ),
    ]
