# Generated by Django 3.1.3 on 2020-12-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_auto_20201210_2255'),
        ('restaurant', '0029_auto_20201211_0025'),
    ]

    operations = [
    ]
