# Generated by Django 3.1.2 on 2020-12-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_auto_20201211_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='payment_type',
        ),
    ]
