# Generated by Django 3.1.2 on 2020-12-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_remove_deposit_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabooWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Taboo Word',
                'verbose_name_plural': 'Taboo Words',
            },
        ),
    ]
