# Generated by Django 3.1.2 on 2020-12-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0035_auto_20201211_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='compliments',
            name='is_processed',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
