# Generated by Django 3.1.3 on 2020-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_auto_20201211_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quit_request',
            field=models.BooleanField(default=False),
        ),
    ]
