# Generated by Django 3.1.3 on 2020-12-11 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_customer_quit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
